// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-xqnjpZKLvQZb8eyba1IXhQrca2xgvYQ',
    appId: '1:584766969014:web:ce289fd1d62b4113a58217',
    messagingSenderId: '584766969014',
    projectId: 'travelapp-6bfb8',
    authDomain: 'travelapp-6bfb8.firebaseapp.com',
    storageBucket: 'travelapp-6bfb8.appspot.com',
    measurementId: 'G-W53GMEP1NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2t8SwVl8FpCUd8csIHAoiFnjkbcAufSo',
    appId: '1:584766969014:android:cd6bd14d76973aaba58217',
    messagingSenderId: '584766969014',
    projectId: 'travelapp-6bfb8',
    storageBucket: 'travelapp-6bfb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPF8ImRLr7QKXqh0qUTufCWi-1HAkUgFs',
    appId: '1:584766969014:ios:607f56d4b077e870a58217',
    messagingSenderId: '584766969014',
    projectId: 'travelapp-6bfb8',
    storageBucket: 'travelapp-6bfb8.appspot.com',
    iosClientId: '584766969014-58ldi25ve11tcjbjafmm2ccfmuag4cbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPF8ImRLr7QKXqh0qUTufCWi-1HAkUgFs',
    appId: '1:584766969014:ios:607f56d4b077e870a58217',
    messagingSenderId: '584766969014',
    projectId: 'travelapp-6bfb8',
    storageBucket: 'travelapp-6bfb8.appspot.com',
    iosClientId: '584766969014-58ldi25ve11tcjbjafmm2ccfmuag4cbj.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp',
  );
}
